In [2]:
import numpy as np

In [4]:
bidim1=np.array([[18,23,20],[400,300,710]])

In [5]:
bidim1

array([[ 18,  23,  20],
       [400, 300, 710]])

In [6]:
bidim1.shape

(2, 3)

In [7]:
bidim1.ndim

2

In [8]:
bidim1[-1,-1]

710

In [11]:
bidim1[0,0]

18

In [12]:
np.resize(bidim1,(10,10))

array([[ 18,  23,  20, 400, 300, 710,  18,  23,  20, 400],
       [300, 710,  18,  23,  20, 400, 300, 710,  18,  23],
       [ 20, 400, 300, 710,  18,  23,  20, 400, 300, 710],
       [ 18,  23,  20, 400, 300, 710,  18,  23,  20, 400],
       [300, 710,  18,  23,  20, 400, 300, 710,  18,  23],
       [ 20, 400, 300, 710,  18,  23,  20, 400, 300, 710],
       [ 18,  23,  20, 400, 300, 710,  18,  23,  20, 400],
       [300, 710,  18,  23,  20, 400, 300, 710,  18,  23],
       [ 20, 400, 300, 710,  18,  23,  20, 400, 300, 710],
       [ 18,  23,  20, 400, 300, 710,  18,  23,  20, 400]])

In [16]:
bidim2=np.array(range(1,10,2))

In [17]:
bidim2

array([1, 3, 5, 7, 9])

In [18]:
bidim3=np.arange(1,10,2)

In [19]:
bidim3

array([1, 3, 5, 7, 9])

In [20]:
bidim4=np.arange(1,10)

In [21]:
bidim5=np.array([bidim4,bidim4])

In [22]:
bidim5

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
bidim6=np.reshape(np.arange(1,26),[5,5])

In [24]:
bidim6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
bidim7=bidim6.astype("float64")

In [26]:
bidim7

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [27]:
np.eye(3, dtype=int) #Matriz Identidad

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.eye(2,3) #float es el data type default

array([[1., 0., 0.],
       [0., 1., 0.]])

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.empty(shape=(3,3))

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.403e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [33]:
np.full(shape=(3,3), fill_value=False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Ejercicio

In [38]:
Punto1=np.reshape(np.arange(0,9),[3,3])
Punto1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
Punto2=np.identity(6)
Punto2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])