# Numeric Python

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
lista1=[1,2,3]

In [5]:
type(lista1)

list

In [6]:
matriz1=numpy.array(lista1)

In [7]:
type(matriz1)

numpy.ndarray

In [8]:
matriz1

array([1, 2, 3])

In [9]:
matriz1.ndim

1

In [10]:
matriz1.shape

(3,)

In [11]:
lista3=[1.0,True,"a",3]

In [12]:
import numpy as np

In [13]:
matriz3=np.array(lista3)

In [14]:
matriz3

array(['1.0', 'True', 'a', '3'], dtype='<U32')

## Nota: Las Matrices almacenan valores de solo un tipo de dato

In [16]:
matriz1.dtype

dtype('int32')

In [21]:
matriz4=np.array([1,2,3], dtype="float")

In [18]:
matriz4

array([1., 2., 3.])

In [19]:
matriz4.dtype

dtype('float64')

In [22]:
matriz5=np.array([1,2,3], dtype="float16")

In [23]:
matriz5

array([1., 2., 3.], dtype=float16)

In [24]:
m=[1,2,3]
n=[4,5,6]

In [26]:
m+n

[1, 2, 3, 4, 5, 6]

In [27]:
matriz_m=np.array(m)
matriz_n=np.array(n)

In [28]:
matriz_m + matriz_n

array([5, 7, 9])

In [29]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [30]:
matriz_m[0]

1

In [31]:
matriz_n[-1]

6

In [32]:
o=[7,8,9,10]
matriz_o=np.array(o)

In [33]:
matriz_o

array([ 7,  8,  9, 10])

In [34]:
matriz_m + matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [35]:
matriz_neg=matriz_m - matriz_n

In [36]:
matriz_neg

array([-3, -3, -3])

In [37]:
np.absolute(matriz_neg)

array([3, 3, 3])

In [38]:
np.maximum(matriz_m,matriz_n)

array([4, 5, 6])

In [39]:
np.minimum(matriz_m,matriz_n)

array([1, 2, 3])

In [40]:
np.minimum(matriz_m,matriz_m)

array([1, 2, 3])

In [41]:
np.minimum(matriz_m,matriz_o)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [42]:
desordenada=np.array([5,21,8,2,77,38,-90])

In [43]:
desordenada

array([  5,  21,   8,   2,  77,  38, -90])

In [44]:
desordenada.sort()

In [45]:
desordenada

array([-90,   2,   5,   8,  21,  38,  77])

In [46]:
matriz6=np.array(range(1,6))
matriz7=np.array(range(4,11))

In [47]:
matriz6

array([1, 2, 3, 4, 5])

In [49]:
matriz7

array([ 4,  5,  6,  7,  8,  9, 10])

In [50]:
matriz8=np.append(matriz6,matriz7,axis=0)

In [51]:
matriz8

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

# Actividad 1

In [52]:
vector1=np.array(range(3,53))

In [53]:
vector1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])

In [54]:
vector2=np.array([0,1,2,3,4,0,1,2,3,4])

In [55]:
vector2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [56]:
vector2.sort()

In [57]:
vector2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])